import Footer from "@/components/Footer/Footer"
import MusicPlayer from "@/components/MusicPlayer/MusicPlayer"
import "@/styles/index.scss"
import { Poppins } from "next/font/google"
import SiteHeader from "./SiteHeader"
import StoreProvider from "./api/StoreProvider"
import "./globals.css"

export const metadata = {
    title: "Ncmaz - Blog, News, Magazine template",
    description: "Generated by create next app",
}

const poppins = Poppins({
    subsets: ["latin"],
    display: "swap",
    weight: ["300", "400", "500", "600", "700"],
})

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className={poppins.className}>
            <body className="">
                <div className="bg-[#f8f8f8] text-base dark:bg-neutral-900/95 text-neutral-900 dark:text-neutral-200">
                    <StoreProvider>
                        <SiteHeader />
                        {children}
                        <MusicPlayer />
                        <Footer />
                    </StoreProvider>
                </div>
            </body>
        </html>
    )
}
